#!/usr/bin/env python3

"""
Plots the difference in seconds between files in a folder.
Useful(?) to check the linearity of motion control passes.

Usage:
    plot-times <folder>

Options:
    -h -? --help    Show this screen.
    -v --version    Show version.
"""

import os
import time
import exifread
from datetime import timedelta, datetime
from docpie import docpie
import matplotlib.pyplot as plt
import numpy

# Constants
extension = "JPG"   # Case Sensitive
version = (1,0)

# Grab some info
args = docpie(__doc__, version=version)
path = os.path.abspath(args['<folder>'])
files = [f for f in os.scandir(path) if f.name.endswith(extension)]

# Create a list of datetime objects from EXIF DateTimeOriginal + SubSecTimeOriginal
deltas = []
for i in range(len(files)):
    dir_entry = files[i]
    with open(dir_entry, 'rb') as file:
        exif = exifread.process_file(file) # Populate EXIF
        exif_datetime = exif['EXIF DateTimeOriginal']
        exif_subsecs = exif['EXIF SubSecTimeOriginal']
        file_datetime_str = "{}:{}".format(exif_datetime, exif_subsecs)
        file_datetime_object = datetime.strptime(file_datetime_str, "%Y:%m:%d %H:%M:%S:%f")

        # Calculate time difference with previous file
        if i > 0:
            delta = (file_datetime_object - previous).total_seconds()
            deltas += [delta]
        else:
            delta = 0

        previous = file_datetime_object

        print('{} --> {} (Δ +{})'.format(
            dir_entry.name,
            file_datetime_object.strftime("%a %b %d %H:%M:%S:%f"),
            delta))

mean_delta = round(sum(deltas)/len(deltas), 3)
print('Mean Δ: {}'.format(mean_delta))

# Plot some stuff
fig,ax = plt.subplots(figsize=(20, 10))
ax.plot(deltas)
ax.set_title('Seconds per Frame : ' + path)
ax.set_xlabel('frames')
ax.set_ylabel('seconds')
ax.set_ylim(min(deltas)-1,max(deltas)+1)
ax.axhline(mean_delta, linestyle='--', color='r', zorder=2)
ax.text(len(deltas)*1.05,mean_delta,str(mean_delta), verticalalignment='center')
plt.show()
