#!/usr/bin/env python3

"""
Reverses video files. It's surprisingly annoying to do this by hand!
You can input a single file or a folder. It only looks at *.mov files.

Usage:
    reverse-vid <input>

Options:
    -h -? --help    Show this screen.
    -v --version    Show version.
"""

import os
import subprocess
from docpie import docpie


# ----- Logic -----

args = docpie(__doc__, version="1")
path = os.path.abspath(args['<input>'])

queue = []
if os.path.isdir(path):
    queue = [f.path for f in os.scandir(path) if f.name.endswith('.mov')]
elif path.endswith('.mov'):
    queue = [path]
if len(queue) == 0:
    print('No valid files to process')
    quit()

index = 1
total = len(queue)
for file in queue:
    # ffmpeg -i "$INPUT" -vf reverse -vcodec prores_ks -pix_fmt yuva444p10le -profile:v 4444 "$OUTPUT"
    print("\n\nReversing file {} of {}: {}\n".format(index, total, os.path.basename(file)))
    output = os.path.splitext(file)
    output = output[0] + '-reversed' + output[1]
    subprocess.run(['ffmpeg',
                    '-i', file,
                    '-vf', 'reverse',
                    '-vcodec', 'prores_ks', '-pix_fmt', 'yuva444p10le', '-profile:v', '4444',
                    output])
    index += 1
